In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
import pandas as pd
from io import StringIO
import os
import time

In [12]:
# setting the years needed and url to look at player
years = list(range(2017, 2026))
player_name = "jokicni"
year = 2025
url = 'https://www.bettingpros.com/nba/props/nikola-jokic/points/'

In [9]:
# Set up the driver (make sure you have the appropriate driver, such as chromedriver for Chrome)
driver = webdriver.Chrome()

url = "https://www.bettingpros.com/nba/props/nikola-jokic/points/" # URL of the page with the table
driver.get(url) # Navigate to the page

# Optionally, wait for the page to load fully
time.sleep(2)

# Locate the tbody using the XPath
tbody_element = driver.find_element("xpath", '/html/body/div[1]/div/div/div[1]/div/main/div/div/div[2]/section[4]/div/div[2]/table/tbody')
tbody_html = tbody_element.get_attribute('outerHTML') # Get the HTML of the tbody

soup = BeautifulSoup(tbody_html, 'html.parser') # Parse the HTML with BeautifulSoup

# Now you can extract the rows and columns from the tbody
lines = []
pts = []

# Define column indices
LINE_INDEX = 5  # Assuming Line is the first column (index 0)
PTS_INDEX = 6  # Assuming Pts is the second column (index 1)

# Iterate over each row in tbody with class "table-row"
for row in soup.find_all('tr', class_='table-row'):
    # Get all columns (td elements) in the row
    columns = row.find_all('td')
    
    if columns:  # Ensure there are columns
        line = columns[LINE_INDEX].get_text(strip=True)  # Replace LINE_INDEX with the correct index
        pts_data = columns[PTS_INDEX].get_text(strip=True)  # Replace PTS_INDEX with the correct index

        # Append to lists
        lines.append(line)
        pts.append(pts_data)
# Don't forget to close the driver
driver.quit()

In [10]:
prop_df = pd.DataFrame({"Line": lines, "Pts": pts})

In [13]:
with open(f"DataFrames/{player_name}{year}DataFrame.html", encoding="utf-8") as f:
    f.write(df.to_csv('my_dataframe.csv', index=False))

FileNotFoundError: [Errno 2] No such file or directory: 'DataFrames/jokicni2025DataFrame.html'

In [5]:
with open(f"DataFrames/{player_name}{year}DataFrame.html", encoding="utf-8") as f:
    df.to_csv('my_dataframe.csv', index=False)

    Line  Pts
0   30.5  U26
1   29.5  U28
2     NL   38
3   28.5  U27
4   26.5  O28
5   26.5  O28
6   28.5  U17
7   28.5  O33
8   28.5  U20
9   27.5  O35
10  27.5  U27
11  26.5  U20
12  27.5  U24
13  29.5  U10
14  29.5  U19
15  28.5  O35
16  31.5  O46
17  30.5  O41
18  30.5  U23
19  29.5  O36
20  28.5  O37
21  27.5  U27
22  29.5  U25
23  30.5  O32
24  28.5  U27
25  28.5  O34
26  28.5  U20
27  29.5  U16
28  31.5  O48
29  31.5  O56
30  27.5  U27
31  28.5  O38
32  27.5  O28
33  28.5  O30
34  27.5  U22
35  27.5  O34
36  26.5  O33
37  27.5  O37
38  26.5  O30
39  26.5  U23
40  29.5  U28
41  29.5  U27
42  27.5  U26
43    NL   29
44  26.5  O40
45  25.5  O41
46  26.5  U16